package com.workshop.dao;

import com.workshop.po.Mission;
import com.workshop.po.MissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    int countByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    int deleteByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    int insert(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    int insertSelective(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    List<Mission> selectByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    Mission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    int updateByExampleSelective(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    int updateByExample(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    int updateByPrimaryKeySelective(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    int updateByPrimaryKey(Mission record);
}