package com.workshop.po;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.taobao_id
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private String taobaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mobile
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.qq
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.type
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.year
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.end_date
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ps_status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private Integer psStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.rl_status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private Integer rlStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.cv_status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private Integer cvStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.major
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.category
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.expect_dial_time
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private String expectDialTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.image
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.description
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_date
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.taobao_id
     *
     * @return the value of student.taobao_id
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public String getTaobaoId() {
        return taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.taobao_id
     *
     * @param taobaoId the value for student.taobao_id
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setTaobaoId(String taobaoId) {
        this.taobaoId = taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mobile
     *
     * @return the value of student.mobile
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mobile
     *
     * @param mobile the value for student.mobile
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.qq
     *
     * @return the value of student.qq
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.qq
     *
     * @param qq the value for student.qq
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.type
     *
     * @return the value of student.type
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.type
     *
     * @param type the value for student.type
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.year
     *
     * @return the value of student.year
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.year
     *
     * @param year the value for student.year
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.end_date
     *
     * @return the value of student.end_date
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.end_date
     *
     * @param endDate the value for student.end_date
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ps_status
     *
     * @return the value of student.ps_status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public Integer getPsStatus() {
        return psStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ps_status
     *
     * @param psStatus the value for student.ps_status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setPsStatus(Integer psStatus) {
        this.psStatus = psStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.rl_status
     *
     * @return the value of student.rl_status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public Integer getRlStatus() {
        return rlStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.rl_status
     *
     * @param rlStatus the value for student.rl_status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setRlStatus(Integer rlStatus) {
        this.rlStatus = rlStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.cv_status
     *
     * @return the value of student.cv_status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public Integer getCvStatus() {
        return cvStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.cv_status
     *
     * @param cvStatus the value for student.cv_status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setCvStatus(Integer cvStatus) {
        this.cvStatus = cvStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major
     *
     * @return the value of student.major
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major
     *
     * @param major the value for student.major
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.category
     *
     * @return the value of student.category
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.category
     *
     * @param category the value for student.category
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.expect_dial_time
     *
     * @return the value of student.expect_dial_time
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public String getExpectDialTime() {
        return expectDialTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.expect_dial_time
     *
     * @param expectDialTime the value for student.expect_dial_time
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setExpectDialTime(String expectDialTime) {
        this.expectDialTime = expectDialTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.status
     *
     * @return the value of student.status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.status
     *
     * @param status the value for student.status
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.image
     *
     * @return the value of student.image
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.image
     *
     * @param image the value for student.image
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.description
     *
     * @return the value of student.description
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.description
     *
     * @param description the value for student.description
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_date
     *
     * @return the value of student.create_date
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_date
     *
     * @param createDate the value for student.create_date
     *
     * @mbggenerated Tue Apr 05 00:26:25 EDT 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}