package com.workshop.dao;

import com.workshop.po.Freelancer;
import com.workshop.po.FreelancerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FreelancerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    int countByExample(FreelancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    int deleteByExample(FreelancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    int insert(Freelancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    int insertSelective(Freelancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    List<Freelancer> selectByExample(FreelancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    Freelancer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    int updateByExampleSelective(@Param("record") Freelancer record, @Param("example") FreelancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    int updateByExample(@Param("record") Freelancer record, @Param("example") FreelancerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    int updateByPrimaryKeySelective(Freelancer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freelancer
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    int updateByPrimaryKey(Freelancer record);
}