package com.workshop.po;

import java.util.Date;

public class Freelancer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freelancer.id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freelancer.name
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freelancer.qq_name
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private String qqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freelancer.wexin_name
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private String wexinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freelancer.alipay
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private String alipay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freelancer.type
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freelancer.description
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freelancer.create_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freelancer.id
     *
     * @return the value of freelancer.id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freelancer.id
     *
     * @param id the value for freelancer.id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freelancer.name
     *
     * @return the value of freelancer.name
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freelancer.name
     *
     * @param name the value for freelancer.name
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freelancer.qq_name
     *
     * @return the value of freelancer.qq_name
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public String getQqName() {
        return qqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freelancer.qq_name
     *
     * @param qqName the value for freelancer.qq_name
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setQqName(String qqName) {
        this.qqName = qqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freelancer.wexin_name
     *
     * @return the value of freelancer.wexin_name
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public String getWexinName() {
        return wexinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freelancer.wexin_name
     *
     * @param wexinName the value for freelancer.wexin_name
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setWexinName(String wexinName) {
        this.wexinName = wexinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freelancer.alipay
     *
     * @return the value of freelancer.alipay
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public String getAlipay() {
        return alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freelancer.alipay
     *
     * @param alipay the value for freelancer.alipay
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setAlipay(String alipay) {
        this.alipay = alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freelancer.type
     *
     * @return the value of freelancer.type
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freelancer.type
     *
     * @param type the value for freelancer.type
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freelancer.description
     *
     * @return the value of freelancer.description
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freelancer.description
     *
     * @param description the value for freelancer.description
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freelancer.create_date
     *
     * @return the value of freelancer.create_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freelancer.create_date
     *
     * @param createDate the value for freelancer.create_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}