package com.workshop.po;

import java.util.Date;

public class Mission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.student_id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.task_id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.task_type
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    private Integer taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.activity
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    private Integer activity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.freelancer_id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    private Integer freelancerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.description
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.create_date
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.id
     *
     * @return the value of mission.id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.id
     *
     * @param id the value for mission.id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.student_id
     *
     * @return the value of mission.student_id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.student_id
     *
     * @param studentId the value for mission.student_id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.task_id
     *
     * @return the value of mission.task_id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.task_id
     *
     * @param taskId the value for mission.task_id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.task_type
     *
     * @return the value of mission.task_type
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.task_type
     *
     * @param taskType the value for mission.task_type
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.activity
     *
     * @return the value of mission.activity
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public Integer getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.activity
     *
     * @param activity the value for mission.activity
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public void setActivity(Integer activity) {
        this.activity = activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.freelancer_id
     *
     * @return the value of mission.freelancer_id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public Integer getFreelancerId() {
        return freelancerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.freelancer_id
     *
     * @param freelancerId the value for mission.freelancer_id
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public void setFreelancerId(Integer freelancerId) {
        this.freelancerId = freelancerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.description
     *
     * @return the value of mission.description
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.description
     *
     * @param description the value for mission.description
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.create_date
     *
     * @return the value of mission.create_date
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.create_date
     *
     * @param createDate the value for mission.create_date
     *
     * @mbggenerated Wed May 11 01:20:58 EDT 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}