package com.workshop.po;

import java.util.Date;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.freelancer_id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer freelancerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.student_id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.type
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.caculate_salary_method
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer caculateSalaryMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.number
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.start_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.end_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.has_pay
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer hasPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.description
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.freelancer_id
     *
     * @return the value of task.freelancer_id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getFreelancerId() {
        return freelancerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.freelancer_id
     *
     * @param freelancerId the value for task.freelancer_id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setFreelancerId(Integer freelancerId) {
        this.freelancerId = freelancerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.student_id
     *
     * @return the value of task.student_id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.student_id
     *
     * @param studentId the value for task.student_id
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.type
     *
     * @return the value of task.type
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.type
     *
     * @param type the value for task.type
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.caculate_salary_method
     *
     * @return the value of task.caculate_salary_method
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getCaculateSalaryMethod() {
        return caculateSalaryMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.caculate_salary_method
     *
     * @param caculateSalaryMethod the value for task.caculate_salary_method
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setCaculateSalaryMethod(Integer caculateSalaryMethod) {
        this.caculateSalaryMethod = caculateSalaryMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.number
     *
     * @return the value of task.number
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.number
     *
     * @param number the value for task.number
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.start_date
     *
     * @return the value of task.start_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.start_date
     *
     * @param startDate the value for task.start_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.end_date
     *
     * @return the value of task.end_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.end_date
     *
     * @param endDate the value for task.end_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.has_pay
     *
     * @return the value of task.has_pay
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getHasPay() {
        return hasPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.has_pay
     *
     * @param hasPay the value for task.has_pay
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setHasPay(Integer hasPay) {
        this.hasPay = hasPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.description
     *
     * @return the value of task.description
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.description
     *
     * @param description the value for task.description
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_date
     *
     * @return the value of task.create_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_date
     *
     * @param createDate the value for task.create_date
     *
     * @mbggenerated Sat Apr 16 16:14:22 EDT 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}